# Generated by Django 5.0.2 on 2024-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprogress_userstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='chordStats',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='intervalStats',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='melodyStats',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='progressionStats',
        ),
        migrations.AddField(
            model_name='userstats',
            name='progressStats',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='sessionStats',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='type',
            field=models.CharField(default='interval', max_length=20),
        ),
    ]
